const CareerData = [
  {
    id: 1,
    careerType: 'education',
    icon: 'icon-graduation',
    year: '2023 - 2023',
    title: 'Certificate of Completion Frontend Development Course 2023',
    organization: 'Dwaves Foundation',
  },
  {
    id: 2,
    careerType: 'education',
    icon: 'icon-graduation',
    year: '2023 - 2023',
    title: 'Fullstack Web Completed',
    organization: 'Fullstack Web Development - Coderschool',
  },
  {
    id: 3,
    careerType: 'education',
    icon: 'icon-graduation',
    year: '2017 - 2021',
    title: 'Bachelor`s Degree',
    organization: 'Software Engineering - FPT University Hanoi',
  },
  {
    id: 4,
    careerType: 'experience',
    icon: 'icon-briefcase',
    year: '2023 - Current',
    title: 'Mobile Developer',
    organization: 'EBK - Roviholdings',
  },
  {
    id: 5,
    careerType: 'experience',
    icon: 'icon-briefcase',
    year: '2022 - 2023',
    title: 'Front-End Developer',
    organization: 'ICEO Technology',
  },
  {
    id: 6,
    careerType: 'experience',
    icon: 'icon-briefcase',
    year: '2019 - 2020',
    title: 'Front-End Intern',
    organization: 'FPT Software',
  },
]
export default CareerData
